framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
            - public/img/
        missing_import_mode: strict
        # Disable debug mode for Valet compatibility (use compiled assets)
        enabled: true
