<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUlF01aW\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUlF01aW/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerUlF01aW.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerUlF01aW\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerUlF01aW\App_KernelProdContainer([
    'container.build_hash' => 'UlF01aW',
    'container.build_id' => '3fb1e471',
    'container.build_time' => 1776543258,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUlF01aW');
